# hyprspaces-managed settings
plugin {
    hyprspaces {
        paired_offset = 10

        # primary_monitor = <monitor-name>
        # secondary_monitor = <monitor-name>
        # monitors = DP-1,DP-2,HDMI-A-1

        # keep_focused = 1
        # enable_wrapping = 1
        # follow_moved_window = 0
        # persistent_workspaces = 0
        # workspace_names = 1:Web,2:Dev,3:Chat
    }
}
