# hyprspaces-managed wiring
exec-once = hyprctl plugin load "/home/varun/.local/share/hyprspaces/hyprspaces.so"
source = /home/varun/.config/hypr/hyprspaces-plugin-settings.conf
source = /home/varun/.config/hypr/hyprspaces-bindings.conf
